/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_floatwindow_FxService_TrafficDataFloatWindowAdapter_ViewHolder */

#ifndef _Included_com_example_floatwindow_FxService_TrafficDataFloatWindowAdapter_ViewHolder
#define _Included_com_example_floatwindow_FxService_TrafficDataFloatWindowAdapter_ViewHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
