/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <jni.h>
/* Header for class com_example_floatwindow_FxService */

 

/*
JNIEXPORT jstring JNICALL Java_com_xzw_jni_TestJni_hello
  (JNIEnv *, jobject);
jstring
Java_com_xzw_jni_TestJni_hello
  (JNIEnv* env, jobject thiz){
          return (*env)->NewStringUTF(env, "哈哈完成自动化编译 !");
}
*/



/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidWifiRx
 * Signature: (I)J
 */
jlong Java_com_example_floatwindow_FxService_getUidWifiRx
  (JNIEnv* env, jobject thiz){
          return 2;
}

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidWifiTx
 * Signature: (I)J
 */
jlong Java_com_example_floatwindow_FxService_getUidWifiTx
  (JNIEnv *, jclass, jint){
 return 2;
}

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidMobTx
 * Signature: (I)J
 */
jlong Java_com_example_floatwindow_FxService_getUidMobTx
  (JNIEnv *, jclass, jint){
 return 2;
}

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidMobRx
 * Signature: (I)J
 */
jlong Java_com_example_floatwindow_FxService_getUidMobRx
  (JNIEnv *, jclass, jint){
 return 2;
}

 
