/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_floatwindow_FxService */

#ifndef _Included_com_example_floatwindow_FxService
#define _Included_com_example_floatwindow_FxService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_floatwindow_FxService_MODE_PRIVATE
#define com_example_floatwindow_FxService_MODE_PRIVATE 0L
#undef com_example_floatwindow_FxService_MODE_WORLD_READABLE
#define com_example_floatwindow_FxService_MODE_WORLD_READABLE 1L
#undef com_example_floatwindow_FxService_MODE_WORLD_WRITEABLE
#define com_example_floatwindow_FxService_MODE_WORLD_WRITEABLE 2L
#undef com_example_floatwindow_FxService_MODE_APPEND
#define com_example_floatwindow_FxService_MODE_APPEND 32768L
#undef com_example_floatwindow_FxService_MODE_MULTI_PROCESS
#define com_example_floatwindow_FxService_MODE_MULTI_PROCESS 4L
#undef com_example_floatwindow_FxService_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_example_floatwindow_FxService_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_example_floatwindow_FxService_BIND_AUTO_CREATE
#define com_example_floatwindow_FxService_BIND_AUTO_CREATE 1L
#undef com_example_floatwindow_FxService_BIND_DEBUG_UNBIND
#define com_example_floatwindow_FxService_BIND_DEBUG_UNBIND 2L
#undef com_example_floatwindow_FxService_BIND_NOT_FOREGROUND
#define com_example_floatwindow_FxService_BIND_NOT_FOREGROUND 4L
#undef com_example_floatwindow_FxService_BIND_ABOVE_CLIENT
#define com_example_floatwindow_FxService_BIND_ABOVE_CLIENT 8L
#undef com_example_floatwindow_FxService_BIND_ALLOW_OOM_MANAGEMENT
#define com_example_floatwindow_FxService_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_example_floatwindow_FxService_BIND_WAIVE_PRIORITY
#define com_example_floatwindow_FxService_BIND_WAIVE_PRIORITY 32L
#undef com_example_floatwindow_FxService_BIND_IMPORTANT
#define com_example_floatwindow_FxService_BIND_IMPORTANT 64L
#undef com_example_floatwindow_FxService_BIND_ADJUST_WITH_ACTIVITY
#define com_example_floatwindow_FxService_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_example_floatwindow_FxService_CONTEXT_INCLUDE_CODE
#define com_example_floatwindow_FxService_CONTEXT_INCLUDE_CODE 1L
#undef com_example_floatwindow_FxService_CONTEXT_IGNORE_SECURITY
#define com_example_floatwindow_FxService_CONTEXT_IGNORE_SECURITY 2L
#undef com_example_floatwindow_FxService_CONTEXT_RESTRICTED
#define com_example_floatwindow_FxService_CONTEXT_RESTRICTED 4L
#undef com_example_floatwindow_FxService_START_CONTINUATION_MASK
#define com_example_floatwindow_FxService_START_CONTINUATION_MASK 15L
#undef com_example_floatwindow_FxService_START_STICKY_COMPATIBILITY
#define com_example_floatwindow_FxService_START_STICKY_COMPATIBILITY 0L
#undef com_example_floatwindow_FxService_START_STICKY
#define com_example_floatwindow_FxService_START_STICKY 1L
#undef com_example_floatwindow_FxService_START_NOT_STICKY
#define com_example_floatwindow_FxService_START_NOT_STICKY 2L
#undef com_example_floatwindow_FxService_START_REDELIVER_INTENT
#define com_example_floatwindow_FxService_START_REDELIVER_INTENT 3L
#undef com_example_floatwindow_FxService_START_FLAG_REDELIVERY
#define com_example_floatwindow_FxService_START_FLAG_REDELIVERY 1L
#undef com_example_floatwindow_FxService_START_FLAG_RETRY
#define com_example_floatwindow_FxService_START_FLAG_RETRY 2L
#undef com_example_floatwindow_FxService_Debug
#define com_example_floatwindow_FxService_Debug 1L
/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidWifiRx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_floatwindow_FxService_getUidWifiRx
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidWifiTx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_floatwindow_FxService_getUidWifiTx
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidMobTx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_floatwindow_FxService_getUidMobTx
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_floatwindow_FxService
 * Method:    getUidMobRx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_floatwindow_FxService_getUidMobRx
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
